version: '3.8'

services:
  app:
    build: .
    container_name: swiftcodes-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: mongodb://db:27017/swiftdb
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:27017"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    volumes:
      - ./src/main/resources:/app/resources

  db:
    image: mongo:latest
    container_name: swiftcodes-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db


volumes:
  mongodb_data_container:
    driver: local
